name: 自动生成 GitHub Pages
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: 查验
        uses: actions/checkout@v2
      
      - name: 预处理
        run: |
          mkdir docs
          cp Tools/mkdocs.example.yml mkdocs.yml
          cp Start/* docs/
          php autobuild
          
      - name: 打印 mkdocs 配置文件 （调试用）
        run: cat mkdocs.yml
      
      - name: 部署
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
